steps:

  - name: node:12
    entrypoint: npm
    args: ['install']

  - name: node:12
    entrypoint: 'bash'
    args: ["./node_modules/hugo-extended/vendor/hugo"]

  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./public", "gs://tfrere-portfolio-bucket"]