steps:

  - name: 'gcr.io/cloud-builders/npm'
    args: [ 'install' ]
    dir: './'

  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: '/bin/sh'
    args:
    - '-c'
    - |
      curl -sL https://github.com/gohugoio/hugo/releases/download/v0.69.2/hugo_0.81.1_Linux-64bit.tar.gz | tar -zxv
      ./hugo