steps:
  - name: node:12
    entrypoint: npm
    args: ["install"]

  - name: node:12
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - |
        curl -sL https://github.com/gohugoio/hugo/releases/download/v0.81.0/hugo_extended_0.81.0_Linux-64bit.tar.gz | tar -zxv
        ./hugo --minify

  - name: gcr.io/cloud-builders/gcloud:latest
    entrypoint: "ls"
    args: ["-lah", "/workspace"]

  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./public", "gs://tfrere.com"]
