steps:

  - name: node:12
    entrypoint: npm
    args: ['install']

  # - name: node:12
  #   entrypoint: '/bin/sh'
  #   args:
  #   - '-c'
  #   - |
  #     curl -sL https://github.com/gohugoio/hugo/releases/download/v0.81.0/hugo_0.81.0_Linux-64bit.tar.gz | tar -zxv
  #     ./hugo

  - name: node:12
    entrypoint: '/bin/sh'
    args: [./hugo]

  # - name: node:12
  #   entrypoint: npm
  #   args: ['run build']

  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./public", "gs://tfrere-portfolio-bucket"]