baseURL = "https://tfrere.com/"
languageCode = "en-us"
title = "Thibaud FRERE Portfolio"
sectionPagesMenu = "main"
buildFuture = false
staticDir = ["static"]
extensions = [
  "laxHtmlBlocks", # laxer block handling... let's see what this does?
  "hardLineBreak", # newlines result in line breaks
]
timeout = 600000

[markup.goldmark.renderer]
  hardWraps = true

# Highest width is 2500px for landscape and 1500px for portrait.
# This will give both orientations roughly the same resolution and size.
# Every landscape image will also be scaled down to 1500px and 1000px,
# and portrait photos to 1000px and 750px wide.
[params]
landscapePhotoWidths = [2500, 1500, 1000, 500]
portraitPhotoWidths = [1500, 1000, 750, 350]

[imaging]
quality = 70

[build]   
  publishResources = false